name: Reusable Workflow Release 

on:
  repository_dispatch:
    types: [semantic-release]

  workflow_dispatch:

permissions: read-all

jobs:
  pipeline:
    permissions:
      actions: write 
      contents: write
    uses: mBlomsterberg/hanayama-workflows/.github/workflows/reusable_release.yml@main
    secrets: 
      github-token: ${{secrets.PAT}}
          